import sys
from reviewer.config import load_config
from reviewer.github import get_pr_client, get_pr_diff, post_review_comment
from reviewer.ai import review_diff


def filter_diff(diff, config):
    lines = diff.splitlines()
    max_lines = config.get("max_diff_lines", 500)
    if len(lines) > max_lines:
        lines = lines[:max_lines]
        lines.append("... (diff truncated for review)")
    return "\n".join(lines)


def main():
    print("[1/5] Loading config...")
    config = load_config()
    print("[2/5] Connecting to GitHub...")
    repo, pr = get_pr_client()
    print(f"PR #{pr.number}: {pr.title}")
    print("[3/5] Fetching diff...")
    diff = get_pr_diff(pr)
    if not diff.strip():
        print("No changes to review.")
        return
    diff = filter_diff(diff, config)
    print(f"Diff size: {len(diff.splitlines())} lines")
    print("[4/5] Sending diff to Claude...")
    review = review_diff(
        diff=diff,
        pr_title=pr.title,
        pr_body=pr.body or "",
        model=config.get("model"),
    )
    print("[5/5] Posting review comment...")
    body = "## AI Code Review\n\n" + review + "\n\n---\n*Generated by ai-code-reviewer*"
    post_review_comment(pr, body)
    print("Done.")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)